web:
  image: nginx:latest
  ports:
    - "8080:80"
  volumes:
    - ./:/var/www/weather/current
    - ./server/nginx.conf:/etc/nginx/conf.d/default.conf
  links:
    - php

php:
  build: .
  volumes:
    - ./:/var/www/weather/current
